// AI image generation for admin CRUD forms. ADMIN only.
//
// Mirrors /api/admin/upload's contract exactly — same { key, src } response
// shape — so ImageField's existing "set the hidden key input" logic works
// unchanged regardless of whether the image was uploaded or generated.
//
// The generated bytes go through the SAME sniffImage() + putObject() pipeline
// a manual upload does. That matters: Gemini choosing to return, say, an SVG
// (it won't, but "won't" is not a security boundary) gets rejected by the same
// magic-byte check that protects the upload route, not trusted because the
// source was "our own AI call" rather than a stranger's file picker.
import crypto from "crypto";
import type { NextRequest } from "next/server";

import { generateImage, isGeminiConfigured } from "@/lib/gemini-image";
import { CONTENT_IMAGE_PREFIX, imageSrc, sniffImage } from "@/lib/images";
import { isR2Configured, putObject } from "@/lib/r2";
import { apiError, apiResponse, invalidInput } from "@/lib/response";
import { requireAdmin } from "@/lib/session";

export const runtime = "nodejs";

const MAX_PROMPT_LENGTH = 2000;

export async function POST(req: NextRequest) {
  try {
    const admin = await requireAdmin();
    if (!admin) return apiResponse(403, "Forbidden");

    if (!isGeminiConfigured()) {
      return apiResponse(
        503,
        "AI image generation is not configured (GEMINI_API_KEY missing)",
      );
    }
    if (!isR2Configured()) {
      return apiResponse(
        503,
        "Image storage is not configured (R2 env vars missing)",
      );
    }

    let body: unknown;
    try {
      body = await req.json();
    } catch {
      return invalidInput();
    }

    const prompt =
      typeof body === "object" && body !== null && "prompt" in body
        ? String((body as { prompt: unknown }).prompt ?? "")
        : "";
    const trimmed = prompt.trim();
    if (!trimmed) return apiResponse(400, "Prompt is empty");
    if (trimmed.length > MAX_PROMPT_LENGTH) {
      return apiResponse(
        400,
        `Prompt is too long — keep it under ${MAX_PROMPT_LENGTH} characters`,
      );
    }

    const result = await generateImage(trimmed);
    if (!result) {
      return apiResponse(
        502,
        "Image generation failed — try again, or adjust the prompt",
      );
    }

    const sniffed = sniffImage(new Uint8Array(result.bytes));
    if (!sniffed) {
      return apiResponse(
        502,
        "The generated image came back in an unsupported format — try again",
      );
    }

    // "ai/" sub-prefix distinguishes generated images from human uploads in
    // storage, e.g. for a future "AI-generated" badge or an audit pass —
    // without changing anything callers rely on (still just an opaque key).
    const stamp = new Date().toISOString().slice(0, 7); // yyyy-mm
    const key = `${CONTENT_IMAGE_PREFIX}ai/${stamp}/${crypto.randomBytes(8).toString("hex")}.${sniffed.ext}`;

    await putObject({
      key,
      body: result.bytes,
      contentType: sniffed.contentType,
    });

    return apiResponse(200, "Generated", { key, src: imageSrc(key) });
  } catch (err) {
    return apiError("admin/generate-image", err);
  }
}
